export const API = {
  BASE: 'api/v1',
  ADMIN: {
    AGENCIES: '/admin/agencies',
    BUDGET_SOURCES: '/admin/budget-sources',
    BUDGET_TYPES: '/admin/budget-types',
    CATEGORIES: '/admin/categories',
    DEPARTMENTS: '/admin/departments',
    IMPL_TYPES: '/admin/project-impl-types',
    PERMISSIONS: '/admin/permissions',
    PROJECT_CATEGORIES: '/admin/project-categories',
    PROJECT_TYPES: '/admin/project-types',
    PROJECTS: '/admin/projects',
    USER_ROLES: '/admin/user-roles',
    USERS: '/admin/users',
  },
  USER: {
    ACCOUNTS: '/user/accounts',
    ACTION_HISTORY: '/user/action-history',
    ISSPS: '/user/issps',
  },
  AUTH: {
    LOGIN: '/auth/login',
    REFRESH_TOKEN: '/auth/refresh-token',
    LOGOUT_ALL: '/auth/logout-from-all-devices',
    ME: '/auth/me',
    REGISTER: '/auth/register',
    ACTION_HISTORY: '/user/action-history',
  },
};
