import { ISSP } from './issp';

export const isspList: ISSP[] = [
  {
    Id: 1,
    isspType: 'primary',
    isspFramework: 'DILG',
    Time: '2018-2020',
    isspName: 'ISSP 2018-2020',
    Update: 'Updated 14 Mar 2024',
  },
  {
    Id: 2,
    isspType: 'error',
    isspFramework: 'Angular',
    Time: '90 min',
    isspName: 'Angular issp',
    Update: 'Updated 25 Jan 2020',
  },
  {
    Id: 3,
    isspType: 'warning',
    isspFramework: 'Android',
    Time: '30 min',
    isspName: 'Android Crash issp',
    Update: 'Updated 30 Jan 2020',
  },
  {
    Id: 4,
    isspType: 'accent',
    isspFramework: 'Design',
    Time: '50 min',
    isspName: 'Web Designing issp',
    Update: 'Updated 01 Feb 2020',
  },
  {
    Id: 5,
    isspType: 'primary',
    isspFramework: 'Web',
    Time: '120 min',
    isspName: 'Basics of TypeScript',
    Update: 'Updated 15 Feb 2020',
  },
  {
    Id: 6,
    isspType: 'warning',
    isspFramework: 'Android',
    Time: '60 min',
    isspName: 'Android N: Quick Settings',
    Update: 'Updated 16 Feb 2020',
  },
  {
    Id: 7,
    isspType: 'primary',
    isspFramework: 'Web',
    Time: '90 min',
    isspName: 'First Progressive Web App',
    Update: 'Updated 18 Feb 2020',
  },
  {
    Id: 8,
    isspType: 'error',
    isspFramework: 'Angular',
    Time: '150 min',
    isspName: 'Basics of Angular',
    Update: 'Updated 20 Feb 2020',
  },
  {
    Id: 9,
    isspType: 'accent',
    isspFramework: 'Design',
    Time: '80 min',
    isspName: 'PSD to HTML From Scratch',
    Update: 'Updated 21 Feb 2020',
  },
];
